### ISSUE TITLE
thanks for the great program.

### ISSUE THREAD

**Issue by byisak** [3Alan/chatgpt-pdf-demo#3]
thanks for the great program
What value is OPENAI_API_PROXY in .env file to get?

**Comment by 3Alan** [comment]
Due to some regions' inability to access OpenAI's API (such as China), I have provided OPENAI_API_PROXY (which will replace https://api.openai.com/). If you can access OpenAI's API normally, you do not need to set it.

**Comment by byisak** [comment]
Thank you for answer. By the way, const [file, setFile] = useState<File | string>(''); I corrected it. When uploading a pdf, the "start reading" button disappears and the pdf preview appears. Do I need to modify other parts as well?

**Comment by 3Alan** [comment]
I fixed the problem and you can refer to my [blog](https://www.alanwang.site/en/blog/chatgpt-pdf#how-to-run-demo-locally) to run the program locally

**Comment by byisak** [comment]
thank you...^^
It works fine. have a good day.!
